_BASE_: Base-Cityscapes-SemanticSegmentation_finetune.yaml
MODEL:
  META_ARCHITECTURE: "HRNet_W48_Finetune_ARCH"
  PRETRAINING: False
  SEM_SEG_HEAD:
    NAME: "HRNet_W48_llama"
    OUTPUT_FEAT_DIM: 512
    BN_TYPE: "torchsyncbn"
  GNN:
    GNN_MODEL_NAME: "Learnable_Topology_BGNN_llama"
    NFEAT: 4096
    NFEAT_OUT: 2048
    nfeat_adj: 256
    adj_feat_dim: 512
    dropout_rate: 0.5
    threshold_value: 0.95
    calc_bipartite: False
    output_max_adj: True
    output_softmax_adj: True
    uot_ratio: 1.0
    mse_or_adv: "None"
    GNN_type: "GSAGE"
    with_datasets_aux: False
    init_stage_iters: -1
    isGumbelSoftmax: False
    GNN_ITERS: 20000
    SEG_ITERS: 20000
    FIRST_STAGE_GNN_ITERS: 15000
    FINETUNE_STAGE1_ITERS: 50000
    INIT_ADJ_PATH: None